[versions]
agp = "8.13.1"
kotlin = "2.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
androidxJunit = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2025.12.00"
materialVersion = "1.13.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxComposeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidxComposeMaterial = { group = "androidx.compose.material", name = "material" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
googleMaterial = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
androidxConstraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
